# Generated by Django 3.2.7 on 2021-10-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InktoberSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('prompt_submission', models.CharField(max_length=200)),
            ],
        ),
    ]
