# Generated by Django 3.2.7 on 2021-10-13 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InktoberSite', '0003_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='prompt_submission',
            new_name='prompt',
        ),
    ]
